services:
  backend:
    build: backend
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - 7000:7000
  postgres:
    image: postgres    
    env_file:
      - .env
    volumes:
      - ./dataset:/docker-entrypoint-initdb.d
  