services:
  backend:
    build: backend
    env_file:
      - .env
    depends_on:
      - postgres
  nginx:
    build: nginx
    ports:
      - 7000:7000
    depends_on:
      - backend
  postgres:
    image: postgres    
    env_file:
      - .env
    volumes:
      - ./dataset:/docker-entrypoint-initdb.d
  frontend:
    build: frontend
    env_file:
      - .env